/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;
import ec.edu.espe.mothersApp.model.PediatricGrowthValidator;
import ec.edu.espe.mothersApp.controller.PediatricGrowthController;
/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class PediatricGrowthGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PediatricGrowthGUI.class.getName());
    private final PediatricGrowthController controller;
    
    public PediatricGrowthGUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.controller = new PediatricGrowthController();
        resetResultLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblbabyData = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblmotherData = new javax.swing.JLabel();
        lblWeightkg = new javax.swing.JLabel();
        lblHeight1 = new javax.swing.JLabel();
        txtWeightkg = new javax.swing.JTextField();
        txtHeight1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        lblNORMAL = new javax.swing.JLabel();
        lblLOWRISK = new javax.swing.JLabel();
        lblSEVERE = new javax.swing.JLabel();
        lblVALIDATE = new javax.swing.JLabel();
        btnvalidateGrowth = new javax.swing.JButton();
        btnclearFields = new javax.swing.JButton();
        btnbackMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 235, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        lblbabyData.setText("Datos del bebé");

        lblWeight.setText("Peso (g)");

        lblHeight.setText("Altura (cm)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblbabyData)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWeight)
                        .addGap(18, 18, 18)
                        .addComponent(txtWeight))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblbabyData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(227, 227, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblmotherData.setText("Datos de la madre");

        lblWeightkg.setText("Peso (Kg)");

        lblHeight1.setText("Altura (cm)");

        txtWeightkg.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtWeightkgAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmotherData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWeightkg)
                    .addComponent(lblHeight1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWeightkg)
                    .addComponent(txtHeight1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmotherData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeightkg)
                    .addComponent(txtWeightkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight1)
                    .addComponent(txtHeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(227, 227, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblResult.setText("Resultado");

        lblNORMAL.setBackground(new java.awt.Color(222, 222, 249));
        lblNORMAL.setText("NORMAL — Peso del bebé ≥ 2500 g y talla ≥ 45 cm");

        lblLOWRISK.setBackground(new java.awt.Color(228, 228, 255));
        lblLOWRISK.setText("BAJO RIESGO — Peso ≥ 1800 g y talla ≥ 35 cm");

        lblSEVERE.setText("GRAVE — Por debajo de los umbrales mínimos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNORMAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLOWRISK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSEVERE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNORMAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLOWRISK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSEVERE, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVALIDATE.setFont(new java.awt.Font("Bodoni MT", 3, 36)); // NOI18N
        lblVALIDATE.setText("Validar el crecimiento pediátrico");

        btnvalidateGrowth.setBackground(new java.awt.Color(227, 227, 252));
        btnvalidateGrowth.setText("Validar el crecimiento");
        btnvalidateGrowth.addActionListener(this::btnvalidateGrowthActionPerformed);

        btnclearFields.setBackground(new java.awt.Color(227, 227, 252));
        btnclearFields.setText("Borrar campos");
        btnclearFields.addActionListener(this::btnclearFieldsActionPerformed);

        btnbackMenu.setBackground(new java.awt.Color(222, 222, 246));
        btnbackMenu.setText("Regresar al Menú");
        btnbackMenu.addActionListener(this::btnbackMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnvalidateGrowth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnbackMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVALIDATE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVALIDATE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnvalidateGrowth)
                        .addGap(29, 29, 29)
                        .addComponent(btnclearFields)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnbackMenu)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void resetResultLabels() {
        java.awt.Color grayFg = new java.awt.Color(120, 120, 120);
        lblNORMAL.setForeground(grayFg);
        lblLOWRISK.setForeground(grayFg);
        lblSEVERE.setForeground(grayFg);
        lblNORMAL.setOpaque(false);
        lblLOWRISK.setOpaque(false);
        lblSEVERE.setOpaque(false);
    }
    
    
    private void btnvalidateGrowthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidateGrowthActionPerformed
        if (txtWeight.getText().trim().isEmpty() || txtHeight.getText().trim().isEmpty()
            || txtWeightkg.getText().trim().isEmpty() || txtHeight1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please fill in all fields before validating.",
            "Missing Data", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double babyWeightGrams = Double.parseDouble(txtWeight.getText().trim());
        double babyHeight = Double.parseDouble(txtHeight.getText().trim());
        double motherWeight = Double.parseDouble(txtWeightkg.getText().trim());
        double motherHeight = Double.parseDouble(txtHeight1.getText().trim());

        ec.edu.espe.mothersApp.model.PediatricGrowthValidator.babyWeight   = babyWeightGrams;
        ec.edu.espe.mothersApp.model.PediatricGrowthValidator.babyHeight   = babyHeight;
        ec.edu.espe.mothersApp.model.PediatricGrowthValidator.motherWeight = motherWeight;
        ec.edu.espe.mothersApp.model.PediatricGrowthValidator.motherHeight = motherHeight;

        String idInput = javax.swing.JOptionPane.showInputDialog(this, 
            "Enter the Baby ID (Numeric integer):", 
            "Database Requirement", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (idInput == null || idInput.trim().isEmpty()) return; 
        int babyId = Integer.parseInt(idInput.trim());

        String ageInput = javax.swing.JOptionPane.showInputDialog(this, 
            "Enter Baby Age (in months):", 
            "Database Requirement", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (ageInput == null || ageInput.trim().isEmpty()) return;
        int ageMonths = Integer.parseInt(ageInput.trim());

        double babyWeightKg = babyWeightGrams / 1000.0;

        String status = controller.validateGrowth(babyId, babyWeightKg, babyHeight, ageMonths);

        resetResultLabels();

        java.awt.Color greenFg = new java.awt.Color(59, 109, 17);
        java.awt.Color greenBg = new java.awt.Color(234, 243, 222);
        java.awt.Color amberFg = new java.awt.Color(133, 79, 11);
        java.awt.Color amberBg = new java.awt.Color(250, 238, 218);
        java.awt.Color dimFg   = new java.awt.Color(180, 180, 180);

        javax.swing.border.Border padding = javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8);

        if ("Normal".equalsIgnoreCase(status)) {
            lblNORMAL.setText(" NORMAL — Verified by database analysis.");
            lblNORMAL.setForeground(greenFg);
            lblNORMAL.setBackground(greenBg);
            lblNORMAL.setOpaque(true);
            lblNORMAL.setBorder(padding);
            lblLOWRISK.setForeground(dimFg);
            lblSEVERE.setForeground(dimFg);
        } else {
            lblLOWRISK.setText(" UNDERWEIGHT — System alert: " + babyWeightKg + "kg is under threshold.");
            lblLOWRISK.setForeground(amberFg);
            lblLOWRISK.setBackground(amberBg);
            lblLOWRISK.setOpaque(true);
            lblLOWRISK.setBorder(padding);
            lblNORMAL.setForeground(dimFg);
            lblSEVERE.setForeground(dimFg);
        }

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Pediatric metrics processed!\nResult: " + status + "\nUploaded to collection 'PediatricGrowths' successfully.", 
            "Data Persisted", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter valid numeric values (e.g., Weight: 3100, Height: 49.5).",
            "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnvalidateGrowthActionPerformed

    private void txtWeightkgAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtWeightkgAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightkgAncestorAdded

    private void btnbackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackMenuActionPerformed
        MenuMothers menu = new MenuMothers();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnbackMenuActionPerformed

    private void btnclearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearFieldsActionPerformed
    txtWeight.setText("");
        txtHeight.setText("");
        txtWeightkg.setText("");
        txtHeight1.setText("");
        resetResultLabels();
        lblNORMAL.setText(" NORMAL — Baby weight ≥ 2500g and height ≥ 45cm");
        lblLOWRISK.setText("LOW RISK — Weight ≥ 1800g and height ≥ 35cm");
        lblSEVERE.setText(" SEVERE — Below minimum thresholds");
        lblNORMAL.setBorder(null);
        lblLOWRISK.setBorder(null);
        lblSEVERE.setBorder(null);
    }//GEN-LAST:event_btnclearFieldsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ec.edu.espe.mothersApp.view.gui.PediatricGrowthGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbackMenu;
    private javax.swing.JButton btnclearFields;
    private javax.swing.JButton btnvalidateGrowth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight1;
    private javax.swing.JLabel lblLOWRISK;
    private javax.swing.JLabel lblNORMAL;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSEVERE;
    private javax.swing.JLabel lblVALIDATE;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeightkg;
    private javax.swing.JLabel lblbabyData;
    private javax.swing.JLabel lblmotherData;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHeight1;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtWeightkg;
    // End of variables declaration//GEN-END:variables
}
