/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;

/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class AlarmValidatorGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlarmValidatorGUI.class.getName());

    
    public AlarmValidatorGUI() {
        initComponents(); 
        javax.swing.SpinnerNumberModel modeloTemp = new javax.swing.SpinnerNumberModel(
            36.8, 30.0, 42.0, 0.1
        );
        spnTemperature.setModel(modeloTemp);
        lblcriticalRisk.setText("");
        lblcriticalRisk.setOpaque(false);
        btnclassifyRiks.addActionListener(this::btnclassifyRiksActionPerformed);
        btnbacktoMenu.addActionListener(this::btnbacktoMenuActionPerformed);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        lblBabyVitalSigns = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        spnTemperature = new javax.swing.JSpinner();
        lblSymptoms = new javax.swing.JLabel();
        chkRespiratorydistress = new javax.swing.JCheckBox();
        chkFeedingproblems = new javax.swing.JCheckBox();
        chkAbnormalskincolor = new javax.swing.JCheckBox();
        chkLethargy = new javax.swing.JCheckBox();
        btnclassifyRiks = new javax.swing.JButton();
        btnclearFields = new javax.swing.JButton();
        btnbacktoMenu = new javax.swing.JButton();
        lblcriticalRisk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 239, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblBabyVitalSigns.setText("Signos Vitales del Bebé");

        lblTemperature.setText("Temperatura (°C)");

        lblSymptoms.setText("Síntomas");

        chkRespiratorydistress.setText("Dificultad respiratoria");
        chkRespiratorydistress.addActionListener(this::chkRespiratorydistressActionPerformed);

        chkFeedingproblems.setText("Problemas de alimentación");

        chkAbnormalskincolor.setText("Color de piel anormal");

        chkLethargy.setText("Letargo / llanto inconsolable");
        chkLethargy.addActionListener(this::chkLethargyActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBabyVitalSigns)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTemperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnTemperature))
                    .addComponent(lblSymptoms)
                    .addComponent(chkRespiratorydistress)
                    .addComponent(chkFeedingproblems)
                    .addComponent(chkAbnormalskincolor)
                    .addComponent(chkLethargy))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBabyVitalSigns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature)
                    .addComponent(spnTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSymptoms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkRespiratorydistress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFeedingproblems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAbnormalskincolor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLethargy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnclassifyRiks.setBackground(new java.awt.Color(239, 239, 253));
        btnclassifyRiks.setText("Clasificar Riesgo");
        btnclassifyRiks.addActionListener(this::btnclassifyRiksActionPerformed);

        btnclearFields.setBackground(new java.awt.Color(235, 235, 250));
        btnclearFields.setText("Limpiar Campos");
        btnclearFields.addActionListener(this::btnclearFieldsActionPerformed);

        btnbacktoMenu.setBackground(new java.awt.Color(236, 236, 253));
        btnbacktoMenu.setText("Volver al Menú");
        btnbacktoMenu.addActionListener(this::btnbacktoMenuActionPerformed);

        lblcriticalRisk.setForeground(new java.awt.Color(255, 51, 51));
        lblcriticalRisk.setText("RIESGO CRÍTICO — Se requiere atención hospitalaria inmediata.");

        jLabel1.setText("CLASIFICADOR DE RIESGO DE SALUD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbacktoMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnclearFields, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclassifyRiks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblcriticalRisk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnclassifyRiks)
                        .addGap(18, 18, 18)
                        .addComponent(btnclearFields)
                        .addGap(18, 18, 18)
                        .addComponent(btnbacktoMenu)))
                .addGap(18, 18, 18)
                .addComponent(lblcriticalRisk)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearFieldsActionPerformed
        spnTemperature.setValue(36.8);
        chkRespiratorydistress.setSelected(false);
        chkFeedingproblems.setSelected(false);
        chkAbnormalskincolor.setSelected(false);
        chkLethargy.setSelected(false);
        lblcriticalRisk.setText("");
        lblcriticalRisk.setOpaque(false);
        lblcriticalRisk.setBorder(null);
    }//GEN-LAST:event_btnclearFieldsActionPerformed

    private void btnclassifyRiksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclassifyRiksActionPerformed
    double temp        = (Double) spnTemperature.getValue();
    boolean respiratory = chkRespiratorydistress.isSelected();
    boolean feeding     = chkFeedingproblems.isSelected();
    boolean skin        = chkAbnormalskincolor.isSelected();
    boolean lethargy    = chkLethargy.isSelected();

    ec.edu.espe.mothersApp.controller.AlarmValidatorController controller = new ec.edu.espe.mothersApp.controller.AlarmValidatorController();
    String result = controller.validateAndSaveAssessment(temp, respiratory, feeding, skin, lethargy);

    if (result.contains("CRITICAL")) {
        lblcriticalRisk.setText(result);
        lblcriticalRisk.setForeground(new java.awt.Color(163, 45, 45));
        lblcriticalRisk.setBackground(new java.awt.Color(252, 235, 235));
    } else {
        lblcriticalRisk.setText(result);
        lblcriticalRisk.setForeground(new java.awt.Color(59, 109, 17));
        lblcriticalRisk.setBackground(new java.awt.Color(234, 243, 222));
    }
    lblcriticalRisk.setOpaque(true);
    lblcriticalRisk.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
    }//GEN-LAST:event_btnclassifyRiksActionPerformed

    private void btnbacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktoMenuActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnbacktoMenuActionPerformed

    private void chkRespiratorydistressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRespiratorydistressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRespiratorydistressActionPerformed

    private void chkLethargyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLethargyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLethargyActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlarmValidatorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbacktoMenu;
    private javax.swing.JButton btnclassifyRiks;
    private javax.swing.JButton btnclearFields;
    private javax.swing.JCheckBox chkAbnormalskincolor;
    private javax.swing.JCheckBox chkFeedingproblems;
    private javax.swing.JCheckBox chkLethargy;
    private javax.swing.JCheckBox chkRespiratorydistress;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBabyVitalSigns;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblcriticalRisk;
    private javax.swing.JSpinner spnTemperature;
    // End of variables declaration//GEN-END:variables
}
