/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;

import ec.edu.espe.mothersApp.controller.EducationalResourceController;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class EducationalResource extends javax.swing.JFrame {
    private int currentTipIndex = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EducationalResource.class.getName());
        private EducationalResourceController controller;
        
    private final String[] imagenesSlides = {
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_0.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_1.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_2.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_3.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_4.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_5.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_6.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_7.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_8.png",
        "/ec/edu/espe/mothersApp/view/gui/Images/imagenes_separadas/imagen_9.png"
    };
    
    public EducationalResource() {
        initComponents();
        this.controller = new ec.edu.espe.mothersApp.controller.EducationalResourceController();
        updateTipCard();
    }
    private void updateTipCard() {
         mostrarImagen(currentTipIndex);

        lblProgress.setText("Tip " + (currentTipIndex + 1) + " de " + imagenesSlides.length);

        btnPrevious.setEnabled(currentTipIndex > 0);
        btnNext.setEnabled(currentTipIndex < imagenesSlides.length - 1);

        pnlCard.revalidate();
        pnlCard.repaint();
    }

    private void mostrarImagen(int index) {
       if (index >= 0 && index < imagenesSlides.length) {
        try {
            java.net.URL imgURL = getClass().getResource(imagenesSlides[index]);
            if (imgURL != null) {
                ImageIcon iconOriginal = new ImageIcon(imgURL);

                int ancho = lblImagenSlide.getWidth() > 0 ? lblImagenSlide.getWidth() : 520;
                int alto = lblImagenSlide.getHeight() > 0 ? lblImagenSlide.getHeight() : 380;

                Image imagenEscalada = iconOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                lblImagenSlide.setIcon(new ImageIcon(imagenEscalada));
                lblImagenSlide.setText("");
            } else {
                System.err.println("No se encontró la imagen en: " + imagenesSlides[index]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenSlide = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        cmbTopics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel1.setText("CONSEJOS EDUCATIVOS PARA PADRES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlCard.setBackground(new java.awt.Color(231, 231, 249));
        pnlCard.setBorder(javax.swing.BorderFactory.createTitledBorder("Consejos para Padres"));

        lblImagenSlide.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenSlide, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblProgress.setText("TIP 2");

        btnPrevious.setText("Anterior");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnNext.setText("Siguiente");
        btnNext.addActionListener(this::btnNextActionPerformed);

        cmbTopics.setText("Regresar al Menú");
        cmbTopics.addActionListener(this::cmbTopicsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProgress)
                        .addGap(77, 77, 77)
                        .addComponent(btnPrevious)
                        .addGap(65, 65, 65)
                        .addComponent(btnNext)
                        .addGap(111, 111, 111)
                        .addComponent(cmbTopics)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgress)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(cmbTopics))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (currentTipIndex > 0) {
        currentTipIndex--;
        updateTipCard();
    }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    if (currentTipIndex < imagenesSlides.length - 1) {
        currentTipIndex++;
        updateTipCard();
    }
    }//GEN-LAST:event_btnNextActionPerformed

    private void cmbTopicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTopicsActionPerformed
     MenuMothers menu = new MenuMothers(); 
    menu.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_cmbTopicsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new EducationalResource().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton cmbTopics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagenSlide;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JPanel pnlCard;
    // End of variables declaration//GEN-END:variables
}
