/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;
import org.bson.Document;
import java.util.List;
import ec.edu.espe.mothersApp.controller.InteractiveChatController;
/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class InteractiveChatforMothers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InteractiveChatforMothers.class.getName());
    
private String historialChat = "<html><body style='font-family: sans-serif; padding: 10px; background-color: #f4f6f9;'>";    
private final InteractiveChatController chatController;
    
    public InteractiveChatforMothers() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        jTextPane1.setContentType("text/html");
    jTextPane1.setEditable(false);
    
    this.chatController = new ec.edu.espe.mothersApp.controller.InteractiveChatController();
    
    cargarHistorialDesdeNube();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ButtonSend = new javax.swing.JButton();
        ButtonReply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnReturntoMenu = new javax.swing.JButton();
        btnLimpiarChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 204)));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 48)); // NOI18N
        jLabel1.setText("Chat Interactivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));

        jLabel2.setText("Madre");

        ButtonSend.setBackground(new java.awt.Color(204, 255, 255));
        ButtonSend.setText("Enviar");
        ButtonSend.addActionListener(this::ButtonSendActionPerformed);

        ButtonReply.setBackground(new java.awt.Color(153, 255, 204));
        ButtonReply.setText("Responder");
        ButtonReply.addActionListener(this::ButtonReplyActionPerformed);

        jTextPane1.setBackground(new java.awt.Color(230, 230, 250));
        jTextPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(jTextPane1);

        btnReturntoMenu.setText("Regresar al Menú");
        btnReturntoMenu.addActionListener(this::btnReturntoMenuActionPerformed);

        btnLimpiarChat.setBackground(new java.awt.Color(255, 204, 255));
        btnLimpiarChat.setText("Borrar");
        btnLimpiarChat.addActionListener(this::btnLimpiarChatActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReturntoMenu)
                        .addGap(29, 29, 29)
                        .addComponent(ButtonSend)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonReply)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarChat)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturntoMenu)
                    .addComponent(ButtonSend)
                    .addComponent(ButtonReply)
                    .addComponent(btnLimpiarChat))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReplyActionPerformed
         String Answer = javax.swing.JOptionPane.showInputDialog(this, "Answer:");
    if (Answer != null && !Answer.trim().isEmpty()) {
        try {
            chatController.sendMessage("Chat", Answer.trim());
            agregarMensajeAlChat("Chat", Answer.trim());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_ButtonReplyActionPerformed

    private void ButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendActionPerformed
        String message = javax.swing.JOptionPane.showInputDialog(this, "Write your mom's question:");
    if (message != null && !message.trim().isEmpty()) {
        try {
            chatController.sendMessage("Mother", message.trim());
            agregarMensajeAlChat("Mother", message.trim());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_ButtonSendActionPerformed

    private void btnReturntoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturntoMenuActionPerformed
    MenuMothers menu = new MenuMothers();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnReturntoMenuActionPerformed

    private void btnLimpiarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarChatActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "¿Deseas limpiar la pantalla del chat?", 
        "Limpiar Chat", 
        javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        chatController.clearChatHistory(); 
        
        jTextPane1.setContentType("text/html");
        jTextPane1.setText("<html><body></body></html>");
        jTextPane1.revalidate();
        jTextPane1.repaint();
    }

    }//GEN-LAST:event_btnLimpiarChatActionPerformed
    private void cargarHistorialDesdeNube() {
        try {
            List<Document> mensajesGuardados = chatController.viewMessages();
            for (Document doc : mensajesGuardados) {
                String sender = doc.getString("sender");
                String message = doc.getString("message");
             
                agregarMensajeAlChat(sender, message);
            }
        } catch (Exception e) {
            System.err.println("Error al recuperar el historial del chat: " + e.getMessage());
        }
    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InteractiveChatforMothers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReply;
    private javax.swing.JButton ButtonSend;
    private javax.swing.JButton btnLimpiarChat;
    private javax.swing.JButton btnReturntoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void agregarMensajeAlChat(String remitente, String mensaje) {
        String burbuja = " ";
        
        if (remitente.equalsIgnoreCase("Mother")) {
            burbuja = "<div style='text-align: right; margin-bottom: 10px;'>"
                    + "<span style='background-color: #d9fdd3; padding: 8px 14px; "
                    + "border-radius: 12px; display: inline-block; max-width: 70%; text-align: left; "
                    + "border: 1px solid #c2ebd0; color: #111b21;'> "
                    + "<b>Mother:</b> " + mensaje
                    + "</span></div>";
        } else {
            burbuja = "<div style='text-align: left; margin-bottom: 10px;'>"
                    + "<span style='background-color: #ffffff; padding: 8px 14px; "
                    + "border-radius: 12px; display: inline-block; max-width: 70%; "
                    + "border: 1px solid #e1e4e8; color: #111b21;'>"
                    + "<b>Chat:</b> " + mensaje
                    + "</span></div>";
        }
        
        historialChat += burbuja;
        jTextPane1.setText(historialChat + "</body></html>");
       
    }
}
