/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;

/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class MenuMothers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMothers.class.getName());

    
    public MenuMothers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        InteractiveChat = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MnuScheduleAppointment = new javax.swing.JMenuItem();
        MnuDoctor = new javax.swing.JMenuItem();
        MnuMedicalRecord = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 243, 255));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 48)); // NOI18N
        jLabel1.setText("Maternidad Valiente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 204));

        jMenu1.setBackground(new java.awt.Color(204, 255, 255));
        jMenu1.setText("Sistema");

        jMenu6.setText("Registrar");

        jMenuItem1.setText("Madre");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu6.add(jMenuItem1);

        jMenuItem4.setText("Bebé");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu6.add(jMenuItem4);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu4.setBackground(new java.awt.Color(204, 255, 204));
        jMenu4.setText("Comunidad y Educación");

        InteractiveChat.setText("Chat Interactivo");
        InteractiveChat.addActionListener(this::InteractiveChatActionPerformed);
        jMenu4.add(InteractiveChat);

        jMenuItem12.setText("Recurso Educativo");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Diagnóstico y Alertas");

        jMenuItem9.setText("Clasificar el nivel de riesgo para la salud");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Gestión Médica");

        jMenuItem5.setText("Calcular la semana de gestación");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Validar el crecimiento ");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Gestionar cita médica");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        MnuScheduleAppointment.setText("Programar cita");
        MnuScheduleAppointment.addActionListener(this::MnuScheduleAppointmentActionPerformed);
        jMenu2.add(MnuScheduleAppointment);

        MnuDoctor.setText("Doctor");
        MnuDoctor.addActionListener(this::MnuDoctorActionPerformed);
        jMenu2.add(MnuDoctor);

        MnuMedicalRecord.setText("Historial médico");
        MnuMedicalRecord.addActionListener(this::MnuMedicalRecordActionPerformed);
        jMenu2.add(MnuMedicalRecord);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
Mother motherWindow = new Mother();
motherWindow.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
     Baby babyWindow = new Baby();
    babyWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
    EducationalResource eduWindow = new EducationalResource();
    eduWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    ManagementWeekCalculator gestWindow = new ManagementWeekCalculator();
    gestWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        PediatricGrowthGUI growthWindow = new PediatricGrowthGUI();
    growthWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        MedicalAppointmentReminder apptWindow = new MedicalAppointmentReminder();
    apptWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void InteractiveChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InteractiveChatActionPerformed
    InteractiveChatforMothers chatWindow = new InteractiveChatforMothers ();
    chatWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_InteractiveChatActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        AlarmValidatorGUI riskWindow = new AlarmValidatorGUI(); 
    riskWindow.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void MnuScheduleAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuScheduleAppointmentActionPerformed
        ScheduleAppointmentGUI appointmentWindow = new ScheduleAppointmentGUI();
        appointmentWindow.setVisible(true);
        appointmentWindow.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_MnuScheduleAppointmentActionPerformed

    private void MnuDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuDoctorActionPerformed
        FrmDoctor doctorWindow = new FrmDoctor();
        doctorWindow.setVisible(true);
        doctorWindow.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_MnuDoctorActionPerformed

    private void MnuMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMedicalRecordActionPerformed
        FrmMedicalRecord recordWindow = new FrmMedicalRecord();
        recordWindow.setVisible(true);
        recordWindow.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_MnuMedicalRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMothers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InteractiveChat;
    private javax.swing.JMenuItem MnuDoctor;
    private javax.swing.JMenuItem MnuMedicalRecord;
    private javax.swing.JMenuItem MnuScheduleAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
