/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mothersApp.view.gui;
import ec.edu.espe.mothersApp.model.Appointment;
import ec.edu.espe.mothersApp.controller.ScheduleAppointmentController;

/**
 *
 * @author Jennyfer Nase, Error 404, @ESPE
 */
public class ScheduleAppointmentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScheduleAppointmentGUI.class.getName());
    private final ScheduleAppointmentController controller;
    
    public ScheduleAppointmentGUI() {
        initComponents();
        this.controller = new ScheduleAppointmentController();
        btnsaveAppointment.addActionListener(this::btnsaveAppointmentActionPerformed);
        btnviewAppointments.addActionListener(this::btnviewAppointmentsActionPerformed);
        btnSave.addActionListener(this::btnSaveActionPerformed);
        btnclearFields.addActionListener(this::btnclearFieldsActionPerformed);
        lblappointmentScheduled.setText("");
        lblappointmentScheduled.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtappointmentDate = new javax.swing.JTextField();
        lblappointmentDetails = new javax.swing.JLabel();
        lblappointmentDate = new javax.swing.JLabel();
        lblReminder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtreminder = new javax.swing.JTextField();
        lbldoctorRecommendation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdoctorRecommendation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblappointmentScheduled = new javax.swing.JLabel();
        btnsaveAppointment = new javax.swing.JButton();
        btnviewAppointments = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnclearFields = new javax.swing.JButton();
        btnbackMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 226, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblappointmentDate.setText("Detalles de la cita");

        lblReminder.setText("Recordatorio");

        jScrollPane1.setViewportView(txtreminder);

        lbldoctorRecommendation.setText("Recomendación de la doctora");

        jScrollPane2.setViewportView(txtdoctorRecommendation);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblappointmentDetails)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblappointmentDate)
                                .addGap(18, 18, 18)
                                .addComponent(txtappointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbldoctorRecommendation))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblReminder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblappointmentDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtappointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblappointmentDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReminder))
                .addGap(13, 13, 13)
                .addComponent(lbldoctorRecommendation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel1.setText("Gestionar cita médica");

        lblappointmentScheduled.setText("Cita programada para el 2024-07-15");

        btnsaveAppointment.setBackground(new java.awt.Color(230, 230, 248));
        btnsaveAppointment.setText("Guardar cita");
        btnsaveAppointment.addActionListener(this::btnsaveAppointmentActionPerformed);

        btnviewAppointments.setBackground(new java.awt.Color(229, 229, 255));
        btnviewAppointments.setText("Ver citas");
        btnviewAppointments.addActionListener(this::btnviewAppointmentsActionPerformed);

        btnSave.setBackground(new java.awt.Color(228, 228, 252));
        btnSave.setText("Guardar historial médico");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnclearFields.setBackground(new java.awt.Color(224, 224, 249));
        btnclearFields.setText("Borrar campos");
        btnclearFields.addActionListener(this::btnclearFieldsActionPerformed);

        btnbackMenu.setBackground(new java.awt.Color(227, 227, 248));
        btnbackMenu.setText("Regresar al Menú");
        btnbackMenu.addActionListener(this::btnbackMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnviewAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsaveAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addComponent(btnclearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblappointmentScheduled, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnsaveAppointment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnviewAppointments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnclearFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbackMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblappointmentScheduled)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbackMenuActionPerformed

    private void btnsaveAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveAppointmentActionPerformed
    String date     = txtappointmentDate.getText().trim();
        String reminder = txtreminder.getText().trim();
        if (date.isEmpty()) {
            showStatus(" Please enter an appointment date.", false);
            return;
        }
        boolean success = controller.processScheduleAppointment(date, reminder);
        if (success) {
            showStatus(" Appointment saved to MongoDB Cloud (" + date + ")", true);
        } else {
            showStatus(" Database Failure: Check console logs.", false);
        }
    }//GEN-LAST:event_btnsaveAppointmentActionPerformed

    private void btnviewAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewAppointmentsActionPerformed
    String remoteData = controller.getAllAppointmentsFromDB();
       
        javax.swing.JOptionPane.showMessageDialog(this,
            "=== MONGODB CLUSTER APPOINTMENTS ===\n\n" + remoteData,
            "Active Clinical Database",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnviewAppointmentsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String recommendation = txtdoctorRecommendation.getText().trim();
        if (recommendation.isEmpty()) {
            showStatus("Please enter a doctor recommendation before saving.", false);
            return;
        }
        boolean success = controller.processSaveMedicalHistory(recommendation);
        if (success) {
            showStatus(" Doctor recommendation safely loaded into database.", true);
        } else {
            showStatus(" Connection Failure during insertion.", false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnclearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearFieldsActionPerformed
    txtappointmentDate.setText("");
        txtreminder.setText("");
        txtdoctorRecommendation.setText("");
        lblappointmentScheduled.setText("");
        lblappointmentScheduled.setOpaque(false);
        lblappointmentScheduled.setBorder(null);
    }//GEN-LAST:event_btnclearFieldsActionPerformed
    private void showStatus(String msg, boolean success) {
        lblappointmentScheduled.setText(msg);
        if (success) {
            lblappointmentScheduled.setForeground(new java.awt.Color(59, 109, 17));
            lblappointmentScheduled.setBackground(new java.awt.Color(234, 243, 222));
        } else {
            lblappointmentScheduled.setForeground(new java.awt.Color(133, 79, 11));
            lblappointmentScheduled.setBackground(new java.awt.Color(250, 238, 218));
        }
        lblappointmentScheduled.setOpaque(true);
        lblappointmentScheduled.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 10));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScheduleAppointmentGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnbackMenu;
    private javax.swing.JButton btnclearFields;
    private javax.swing.JButton btnsaveAppointment;
    private javax.swing.JButton btnviewAppointments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReminder;
    private javax.swing.JLabel lblappointmentDate;
    private javax.swing.JLabel lblappointmentDetails;
    private javax.swing.JLabel lblappointmentScheduled;
    private javax.swing.JLabel lbldoctorRecommendation;
    private javax.swing.JTextField txtappointmentDate;
    private javax.swing.JTextField txtdoctorRecommendation;
    private javax.swing.JTextField txtreminder;
    // End of variables declaration//GEN-END:variables
}
